Aeneta/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),  # Incluye las URLs de la aplicación usuarios
    path('', CustomLoginView.as_view(), name='login'),  # El path vacío redirige al login
    path('administracion/', include('administracion.urls', namespace='administracion')),  # Incluye las URLs con el namespace
    path('alumnos/', include('alumnos.urls', namespace='alumnos')),
    path('visitante/', include(('visitante.urls', 'visitante'), namespace='visitante')),
    path('docente/', include('docente.urls', namespace='docente')),
    # ... cualquier otra ruta que necesites ...
]

administracion/urls.py
# administracion/urls.py

from django.urls import path
from django.views.decorators.http import require_POST
from django.contrib.auth.views import LogoutView
from . import views
from .views import (
    AdministracionHomeView,
    AdministracionSubirDoc,
    AdministracionTitulacion,
    AdministracionConvocatorias,
    AdministracionSeminarios,
    AdministracionInformacion,
    # titulacion
    AdministracionTitulacionConvocatorias,
    AdministracionTitulacionCalendario,
    AdministracionTitulacionRegistrar,
    # cuentas
    AdministracionAdminCuentas,
    
    # alumnos
    create_user,
    agregar_convocatoria,
    update_user,
    AdministracionCambiarContrasena,
    AdministracionEditarDatosGenerales,
    obtener_convocatoria,
    editar_convocatoria,
    eliminar_convocatoria,
    AdministracionAlumnos,
    EliminarMaterial,
    EditarMaterial,
    AdministracionDocumentosAlumnos,
    AdministracionDocumentosPrupuestaAlumnos,
    AdministracionDocumentosIndividualAlumnos,
    AdministracionAsignarSinodalesAlumnos,
    AdministracionVerDetallesPropuestaACS
)
from administracion import views
from django.views.decorators.http import require_POST
from django.contrib.auth.views import LogoutView

app_name = 'administracion'  # Este es el namespace que debe coincidir con el utilizado en 'resolve_url'

urlpatterns = [
    path('home/', AdministracionHomeView.as_view(), name='home'),
    path('logout/', require_POST(LogoutView.as_view()), name='admin-logout'),
    
    # Ver información del administrador, edicion de datos y cambio de contraseña
    path('informacion/', AdministracionInformacion.as_view(), name='informacion'),
    path('editar_datos_generales/', AdministracionEditarDatosGenerales.as_view(), name='editar_datos_generales'),
    path('cambiar_contrasena/', AdministracionCambiarContrasena.as_view(), name='cambiar_contrasena'),

    path('subir_documento/', AdministracionSubirDoc.as_view(), name='subir_documento'),
     path('titulacion/', AdministracionTitulacion.as_view(), name='titulacion'),
    #path('seminarios/', AdministracionSeminarios.as_view(), name='seminarios'),
    path('convocatorias/', AdministracionConvocatorias.as_view(), name='convocatorias'),
    
    # path('documento_form/', AdministracionDocumentoFormView.as_view(), name='documento_form'),  # Nueva ruta para el formulario de Documento
    # path('documento_success/', AdministracionDocumentoSuccessView.as_view(), name='documento_success'),  # Nueva ruta para la vista de éxito

    path('seminarios/', views.seminarios, name='seminarios'),
    path('seminarios/eliminar/<int:id>/', views.eliminar_seminario, name='eliminar_seminario'),
    path('seminarios/editar/<int:id>/', views.editar_seminario, name='editar_seminario'),
    
    # titulacion
    path('titulacion/registrar_formas_titulacion/', AdministracionTitulacionRegistrar.as_view(), name='registrar_formas_de_titulacion'),
    path('titulacion/calendario_titulacion/', AdministracionTitulacionCalendario.as_view(), name='calendario_titulacion'),
    path('convocatorias/agregar/', agregar_convocatoria, name='agregar_convocatoria'),
    path('titulacion/convocatorias/obtener/<int:convocatoria_id>/', obtener_convocatoria, name='obtener_convocatoria'),
    path('titulacion/convocatorias/editar/<int:convocatoria_id>/', editar_convocatoria, name='editar_convocatoria'),
    path('titulacion/convocatorias/eliminar/<int:convocatoria_id>/', eliminar_convocatoria, name='eliminar_convocatoria'),
    path('titulacion/documentos_revision/', AdministracionDocumentosAlumnos.as_view(), name='documentos_revision'),


    path('titulacion/convocatorias_titulacion/', AdministracionTitulacionConvocatorias.as_view(), name='convocatorias_titulacion'),
    
    # cuentas
    path('cuentas/administrar_cuentas/', AdministracionAdminCuentas.as_view(), name='administrar_cuentas'),
    path('cuentas/crear_cuentas/', views.create_user, name='crear_cuentas'),
    path('cuentas/crear-usuario/', create_user, name='create_user'),  # Define la ruta y un nombre para la URL
    path('cuentas/get-user-details/<int:user_id>/', views.get_user_details, name='get-user-details'),
    path('cuentas/update-user/<int:user_id>/', views.update_user, name='update-user'),
    path('cuentas/update-user/<int:user_id>/', update_user, name='update-user'),
    path('cuentas/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('crear_usuario/', views.create_user, name='create_user'),
    
    # alumnos
    path('alumnos/', AdministracionAlumnos.as_view(), name='alumnos'),
    path('eliminar_material/<int:material_id>/', EliminarMaterial.as_view(), name='eliminar_material'),
    path('editar_material/', EditarMaterial.as_view(), name='editar_material'),

    # proceso de titulacion
    path('alumnos/revisar_propuestas_titulacion/', AdministracionDocumentosPrupuestaAlumnos.as_view(), name='revisar_propuestas_titulacion'),
    path('alumnos/individual_revisar_p/<int:pk>/', AdministracionDocumentosIndividualAlumnos.as_view(), name='individual_revisar_p'),
    path('alumnos/asignar_sinodales/<int:pk>/', AdministracionAsignarSinodalesAlumnos.as_view(), name='asignar_sinodales'),
    path('alumnos/ver_detalles/<int:pk>/', AdministracionVerDetallesPropuestaACS.as_view(), name='ver_detalles'),
] 

administracion/views.py
# Agrupar importaciones de django
from django.views.generic import TemplateView, FormView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django import forms
from django.template.loader import render_to_string 
from django.http import JsonResponse, HttpResponse
import json

# Importar módulos específicos
from usuarios.models import CustomUser
from usuarios.forms import CustomUserCreationForm
from .mixins import AdminRequiredMixin
from .models import FormaTitulacion
from .forms import DocumentoForm
from .utils import upload_pdf_admin
from .models import Seminario
from .forms import SeminarioForm, AsignarSinodalesForm

from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import DocumentoForm, RevisarPropuestaForm
from .models import RevisarPropuesta

# Importar excepciones específicas
from smtplib import SMTPAuthenticationError

# Importar vistas genéricas personalizadas
from django.views import View

from .forms import MaterialApoyoForm
from .material_apoyo import upload_pdf
from .models import MaterialApoyo
from alumnos.models import DocumentoPropuestaAlumno, SinodalAsignado, ProcesoTitulacion


# Todo lo necesario para la administracion de titulación
class AdministracionTitulacionRegistrar(AdminRequiredMixin,TemplateView):
    template_name = 'administracion/titulacion/registrar_formas_titulacion.html'


#*****************************************Calendario titulación****************************************************************

class AdministracionTitulacionCalendario(AdminRequiredMixin,TemplateView):
    template_name = 'administracion/titulacion/calendario_titulacion.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['convocatorias'] = FormaTitulacion.objects.all()
        return context

@require_http_methods(["GET", "POST"])
def agregar_convocatoria(request):
    if request.method == 'POST':
        # Crear una instancia del modelo con los datos del formulario
        nueva_convocatoria = FormaTitulacion(
            convocatoria=request.POST['convocatoria'],
            fecha_inicio=request.POST['fecha_inicio'],
            fecha_limite_entrega=request.POST['fecha_limite_entrega'],
            descripcion=request.POST['descripcion'],
            requisitos=request.POST['requisitos'],
            documentos_a_entregar=request.POST['documentos_a_entregar'],
        )
        nueva_convocatoria.save()  # Guardar la instancia en la base de datos

        # Enviar una respuesta JSON indicando éxito
        return JsonResponse({'success': True, 'message': 'Convocatoria agregada correctamente!'})

    # Si no es una solicitud POST, simplemente renderiza el formulario
    return render(request, 'administracion/titulacion/calendario_titulacion.html')

@require_http_methods(["GET"])
def obtener_convocatoria(request, convocatoria_id):
    convocatoria = get_object_or_404(FormaTitulacion, id=convocatoria_id)
    data = {
        'convocatoria': convocatoria.convocatoria,
        'fecha_inicio': convocatoria.fecha_inicio,
        'fecha_limite_entrega': convocatoria.fecha_limite_entrega,
        'descripcion': convocatoria.descripcion,
        'requisitos': convocatoria.requisitos,
        'documentos_a_entregar': convocatoria.documentos_a_entregar,
    }
    return JsonResponse(data)

@require_http_methods(["POST"])
def editar_convocatoria(request, convocatoria_id):
    convocatoria = get_object_or_404(FormaTitulacion, id=convocatoria_id)
    convocatoria.convocatoria = request.POST['convocatoria']
    convocatoria.fecha_inicio = request.POST['fecha_inicio']
    convocatoria.fecha_limite_entrega = request.POST['fecha_limite_entrega']
    convocatoria.descripcion = request.POST['descripcion']
    convocatoria.requisitos = request.POST['requisitos']
    convocatoria.documentos_a_entregar = request.POST['documentos_a_entregar']
    convocatoria.save()
    return JsonResponse({'success': True, 'message': 'Convocatoria actualizada correctamente!'})

@require_http_methods(["POST"])
def eliminar_convocatoria(request, convocatoria_id):
    convocatoria = get_object_or_404(FormaTitulacion, id=convocatoria_id)
    convocatoria.delete()
    return JsonResponse({'success': True, 'message': 'Convocatoria eliminada correctamente!'})

#*****************************************Canvocatorias titulación****************************************************************
class AdministracionTitulacionConvocatorias(AdminRequiredMixin,TemplateView):
    template_name = 'administracion/titulacion/convocatorias_titulacion.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['convocatorias'] = FormaTitulacion.objects.all()
        return context

# Todo lo necesario para el manejo de las cuentas

class AdministracionAdminCuentas(AdminRequiredMixin, TemplateView):
    template_name = 'administracion/cuentas/administrar_cuentas.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Recuperar todos los usuarios
        context['usuarios'] = CustomUser.objects.all()
        return context 

def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            password = form.cleaned_data.get('password1')
            message = 'La cuenta de usuario ha sido creada con éxito.'
            email_content = render_to_string('confirmacion_cuenta.html', {
                'email': user.correo_electronico,
                'password': password
            })
            try:
                send_mail(
                    subject='Confirmación de creación de cuenta',
                    message=email_content,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[user.correo_electronico],
                    fail_silently=False,
                    html_message=email_content
                )
            except SMTPAuthenticationError:
                message += " Pero no se pudo enviar el correo de confirmación."

            return JsonResponse({'status': 'success', 'message': message})
        else:
            errors = form.errors.as_json()
            return JsonResponse({'status': 'error', 'message': 'Por favor corrija los errores en el formulario.', 'errors': errors})
    else:
        form = CustomUserCreationForm()
        return render(request, 'administracion/cuentas/crear_cuentas.html', {'form': form})
    
class AdministracionHomeView(AdminRequiredMixin, TemplateView):
    template_name = 'administracion/home.html'


class AdministracionTitulacion(AdminRequiredMixin, TemplateView):
    template_name = 'administracion/titulacion.html'


class AdministracionConvocatorias(AdminRequiredMixin, TemplateView):
    template_name = 'administracion/convocatorias.html'

class AdministracionSeminarios(AdminRequiredMixin, TemplateView):
    template_name = 'administracion/seminarios.html'

class AdministracionInformacion(AdminRequiredMixin, TemplateView):
    template_name = 'administracion/informacion.html'

class AdministracionEditarDatosGenerales(View):
    def post(self, request):
        try:
            user_data = json.loads(request.body)
            user = request.user  # Asegurarse de que es el usuario actual o buscar por ID si necesario

            # Actualizar campos generales del administrador
            if hasattr(user, 'departamento_admin'):
                user.departamento_admin = user_data.get('departamento_admin', user.departamento_admin)
            if hasattr(user, 'cargo'):
                user.cargo = user_data.get('cargo', user.cargo)

            user.first_name = user_data.get('nombre', user.first_name)
            user.last_name = user_data.get('apellido', user.last_name)
            user.email = user_data.get('correo', user.email)

            user.save()
            return JsonResponse({'status': 'ok', 'message': 'Datos generales del administrador actualizados con éxito'}, status=200)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)

class AdministracionCambiarContrasena(View):
    def post(self, request):
        user = request.user
        data = json.loads(request.body)
        old_password = data.get('old_password', '')
        new_password = data.get('new_password', '')

        if not user.check_password(old_password):
            return JsonResponse({'status': 'error', 'message': 'Contraseña antigua incorrecta'}, status=403)

        if new_password:
            user.set_password(new_password)
        user.save()

        return JsonResponse({'status': 'ok', 'message': 'Contraseña cambiada con éxito'})
# Alumnos
class AdministracionAlumnos(AdminRequiredMixin, View):
    template_name = 'administracion/alumnos.html'

    def get(self, request):
        form = MaterialApoyoForm()
        materiales = MaterialApoyo.objects.all()
        return render(request, self.template_name, {'form': form, 'materiales': materiales})

    def post(self, request):
        form = MaterialApoyoForm(request.POST, request.FILES)
        if form.is_valid():
            archivo = request.FILES['archivo']
            try:
                url = upload_pdf(archivo)
                material_apoyo = form.save(commit=False)
                material_apoyo.url = url
                material_apoyo.save()
            finally:
                archivo.close() 

            return JsonResponse({'success': True})

administracion/templates/base_generic_Administracion.html
<!DOCTYPE html>
{%load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>Página de Administración</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/home_administracion.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/subirDoc.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/informacion.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/nav_bar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/alumno.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/crear_cuentas.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/administrar_cuentas.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/paginacion.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/calendario_titulacion.css' %}">
    
    <!-- Para los iconos-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Para las alertas de SweetAlert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- JavaScrip necesario-->

</head>
<body>
    <div id="nombre_sistema" class="header-flex-container">
        <a href="{% url 'administracion:home' %}">
            <span>Aeneta - Administración</span>
        </a>
        <div class="admin-info">
            {% if nombre_administrador %}
                <!-- Menú desplegable para el administrador -->
                <div class="dropdown_base">
                    <button class="dropbtn_base">{{ nombre_administrador }} {{ apellido_administrador }}</button>
                    <div class="dropdown-content_base">
                        <a href="#" onclick="event.preventDefault(); document.getElementById('view-profile-form').submit();">Ver datos</a>
                        <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Cerrar sesión</a>
                    </div>
                </div>
                <form id="logout-form" action="{% url 'administracion:admin-logout' %}" method="post" style="display:none;">
                    {% csrf_token %}
                </form>
                <form id="view-profile-form" action="{% url 'administracion:informacion' %}" method="get" style="display:none;">
                    <!--no es necesario enviar datos al hacer clic en "Ver datos" -->
                </form>
            {% endif %}
        </div>
    </div>
    <nav class="nav_bar" aria-label="Navegación principal">
        <a class="nav-link" href="{% url 'administracion:subir_documento' %}">Subir documentos</a>

        <!-- Menú desplegable para Titulación -->
        <div class="dropdown">
            <a class="nav-link">Titulación</a>
            <div class="dropdown-content">
                <!-- SUpongo que es mejor que no este
                <a href="{% url 'administracion:registrar_formas_de_titulacion' %}">Registrar formas de titulación</a> 
                -->
                <a href="{% url 'administracion:calendario_titulacion' %}">Calendarios de titulación</a>
            </div>
        </div>

        <!-- Menú desplegable para Alumnos -->
        <div class="dropdown">
            <a class="nav-link" href="{% url 'administracion:alumnos' %}">Alumnos</a>
            <div class="dropdown-content">
                <!-- SUpongo que es mejor que no este
                <a href="{% url 'administracion:registrar_formas_de_titulacion' %}">Registrar formas de titulación</a> 
                -->
                <a href="{% url 'administracion:revisar_propuestas_titulacion' %}">Revisar propuesta de titulación.</a>
            </div>
        </div>
        
        <!-- Menú desplegable para Titulación -->
        <div class="dropdown">
            <a class="nav-link">Cuentas</a>
            <div class="dropdown-content">
                <a href="{% url 'administracion:administrar_cuentas' %}">Administrar cuentas</a>
                <a href="{% url 'administracion:crear_cuentas' %}">Crear cuentas</a>
            </div>
        </div>
        <a class="nav-link" href="{% url 'administracion:seminarios' %}">Seminarios</a>
    </nav>
    
    {% block content %}
    <!-- El contenido específico de cada página irá aquí -->
    {% endblock %}
    <footer>
        <p>Administración - Aeneta - Tiburones 2024 ©</p>
    </footer>
</body>
</html>

administracion/templates/confirmacion_cuenta.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirmación de Cuenta</title>
</head>
<body>
    <h1>¡Bienvenido/a al repositorio Aeneta!</h1>
    <p>Tu cuenta ha sido creada con éxito. A continuación, encontrarás tus datos de acceso:</p>
    <p>Usuario: {{ email }}</p>
    <p>Contraseña: {{ password }}</p> 
    <p>Por favor, asegúrate de cambiar tu contraseña al ingresar por primera vez por motivos de seguridad.</p>
    <p>Si hay algún problema contáctate al correo aeneta.re@gmail.com</p>
</body>
</html>

administracion/templates/correo_propuesta_asignada_sinodal.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Propuesta Asignada</title>
</head>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">Propuesta Asignada</h2>
        <p>Hola {{ nombre_sinodal }},</p>
        <p>Haz sido asignado a la siguiente propuesta:</p>
        <p><strong>Título:</strong> {{ propuesta.titulo }}</p>
        <p><strong>Alumno:</strong> {{ propuesta.alumno.nombre }} {{ propuesta.alumno.apellido }}</p>
        <p>Por favor, revisa los detalles en el sistema.</p>
        <p>Saludos cordiales,</p>
        <p>Repositorio Aeneta</p>
    </div>
</body>
</html>

administracion/templates/correo_propuesta_revisada.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Propuesta Revisada</title>
</head>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">Propuesta Revisada</h2>
        <p>Estimado/a {{ nombre_alumno }} {{ apellido_alumno }},</p>
        <p>Hemos revisado tu propuesta. Para ver los detalles, verifica el estatus en la página web.</p>
        <p>Saludos cordiales,</p>
        <p>Repositorio Aeneta</p>
    </div>
</body>
</html>

administracion/templates/correo_sinodales_asignados_alumno.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sinodales Asignados</title>
</head>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">Sinodales Asignados</h2>
        <p>Estimado/a {{ nombre_alumno }} {{ apellido_alumno }},</p>
        <p>Nos complace informarte que los sinodales asignados a tu propuesta son:</p>
        <ul>
            <li>{{ sinodal_1 }}</li>
            <li>{{ sinodal_2 }}</li>
            <li>{{ sinodal_3 }}</li>
        </ul>
        <p>Saludos cordiales,</p>
        <p>Repositorio Aeneta</p>
    </div>
</body>
</html>