Aeneta/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),  # Incluye las URLs de la aplicación usuarios
    path('', CustomLoginView.as_view(), name='login'),  # El path vacío redirige al login
    path('administracion/', include('administracion.urls', namespace='administracion')),  # Incluye las URLs con el namespace
    path('alumnos/', include('alumnos.urls', namespace='alumnos')),
    path('visitante/', include(('visitante.urls', 'visitante'), namespace='visitante')),
    path('docente/', include('docente.urls', namespace='docente')),
    # ... cualquier otra ruta que necesites ...
]

alumnos/urls.py
# alumnos/urls.py
from django import views
from django.urls import path
from .views import (
    AlumnosHomeView, 
    AlumnosBuscar, 
    AlumnosPreguntas, 
    AlumnosSubirDocumentos, 
    AlumnosTitulacion,
    # titulación
    AlumnosTitulacionCalendario,
    AlumnosTitulacionConvocatoria,
    AlumnosTitulacionForma,
    AlumnosTitulacionEstatus,
    AlumnosInformacion,
    AlumnosCambiarContrasena,
    AlumnosTitulacionMaterial,
    AlumnosVerTrabajo,

    AlumnosProcesoTitulacionInfo,
    ActualizarVerInfo,
    AlumnosProcesoTitulacionEnvPropuesta,
    documento_detalle,
    AlumnosProcesoTitulacionDesarrollo,
    BuscarPorAño,
    BuscarPorPalabra,
    BuscarPorTipo,
    BusquedaAvanzada,
    BuscarLenguajeNatural,
    AlumnosProcesoTitulacionEnvDoc
)
from django.views.decorators.http import require_POST
from django.contrib.auth.views import LogoutView

app_name = 'alumnos'

urlpatterns = [
    path('home/', AlumnosHomeView.as_view(), name='home'),
    path('logout/', require_POST(LogoutView.as_view()), name='alumno-logout'),
    path('buscar/', AlumnosBuscar.as_view(), name='buscar'),
     path('ver_trabajo/<int:pk>/', AlumnosVerTrabajo.as_view(), name='ver_trabajo'),
    path('subir_documento/', AlumnosSubirDocumentos.as_view(), name='subir_documento'),
    path('preguntas_frecuentes/', AlumnosPreguntas.as_view(), name='preguntas_frecuentes'),
    path('titulacion/', AlumnosTitulacion.as_view(), name='titulacion'),

    path('informacion_alumnos/', AlumnosInformacion.as_view(), name='informacion_alumnos'),
    path('cambiar_contrasena/', AlumnosCambiarContrasena.as_view(), name='cambiar_contrasena'),
    # titulación
    path('titulacion/calendario_titulacion/', AlumnosTitulacionCalendario.as_view(), name='calendario_titulacion'),
    path('titulacion/convocatorias_titulacion/', AlumnosTitulacionConvocatoria.as_view(), name='convocatorias_titulacion'),
    path('titulacion/formas_titulacion/', AlumnosTitulacionForma.as_view(), name='formas_titulacion'),
    path('titulacion/estatus_titulacion/', AlumnosTitulacionEstatus.as_view(), name='estatus_titulacion'),
    path('titulacion/material_apoyo/', AlumnosTitulacionMaterial.as_view(), name='material_apoyo'),

    # Porceso de titulacion
    path('proceso_titulacion/informacion/', AlumnosProcesoTitulacionInfo.as_view(), name='informacion'),
    path('proceso_titulacion/actualizar_ver_info/', ActualizarVerInfo.as_view(), name='actualizar_ver_info'),
    path('proceso_titulacion/enviar_propuesta/', AlumnosProcesoTitulacionEnvPropuesta.as_view(), name='enviar_propuesta'),
    path('documento/<int:pk>/', documento_detalle, name='documento_detalle'),
    path('proceso_titulacion/desarrollo/', AlumnosProcesoTitulacionDesarrollo.as_view(), name='desarrollo'),
    path('proceso_titulacion/envio_documento_p',AlumnosProcesoTitulacionEnvDoc.as_view(), name='envio_documento_p'),

    path('buscar_por_tipo/', BuscarPorTipo.as_view(), name='buscar_por_tipo'),
    path('buscar_por_palabra/', BuscarPorPalabra.as_view(), name='buscar_por_palabra'),
    path('buscar_por_año/', BuscarPorAño.as_view(), name='buscar_por_año'),
    path('busqueda_avanzada/', BusquedaAvanzada.as_view(), name='busqueda_avanzada'),
    path('buscar-lenguaje-natural/', BuscarLenguajeNatural.as_view(), name='buscar_lenguaje_natural'),
]

administracion/models.py
from django.db import models

class FormaTitulacion(models.Model):
    convocatoria = models.CharField(max_length=100)
    fecha_inicio = models.DateField()
    fecha_limite_entrega = models.DateField()
    descripcion = models.TextField()
    requisitos = models.TextField()
    documentos_a_entregar = models.TextField()

    def __str__(self):
        return self.convocatoria
    
class Documento(models.Model):
    TIPO_CHOICES = (
        ('TT', 'Trabajo Terminal'),
        ('AR', 'Artículo'),
        ('TS', 'Tesis'),
        ('OT', 'Otro'),
    )
    
    nombre = models.CharField(max_length=255)
    resumen = models.TextField()
    palabras_clave = models.CharField(max_length=255)
    nombre_autor = models.CharField(max_length=100)
    sinodales = models.CharField(max_length=255)
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES)
    fecha_elaboracion = models.DateField()
    convocatoria_titulacion = models.CharField(max_length=100)
    url = models.URLField(blank=True, null=True)  # Hacer el campo opcional

    def __str__(self):
        return self.nombre

class Seminario(models.Model):
    titulo = models.CharField(max_length=200)
    fecha = models.DateField()
    hora = models.TimeField()
    ubicacion = models.CharField(max_length=200)
    descripcion = models.TextField()
    presentador = models.CharField(max_length=100)
    temas = models.TextField()
    requisitos = models.TextField()
    creditos_academicos = models.DecimalField(max_digits=3, decimal_places=1)

    def __str__(self):
        return self.titulo


class MaterialApoyo(models.Model):
    TIPO_CHOICES = [
        ('Guia', 'Guía'),
        ('Formato', 'Formato'),
        ('Ejemplo', 'Ejemplo'),
    ]

    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
    nombre = models.CharField(max_length=255) 
    url = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.tipo} - {self.nombre}"

#Proceso de titulacion

class RevisarPropuesta(models.Model):
    documento_alumno = models.OneToOneField('alumnos.DocumentoPropuestaAlumno', on_delete=models.CASCADE)
    revisado = models.BooleanField(default=False)
    titulo_adecuado = models.BooleanField(null=True, blank=True)
    objetivos_planteados = models.BooleanField(null=True, blank=True)
    referencias_correctas = models.BooleanField(null=True, blank=True)
    errores_ortograficos = models.BooleanField(null=True, blank=True)
    normas_formato = models.BooleanField(null=True, blank=True)
    metodologia_descrita = models.BooleanField(null=True, blank=True)
    suficientes_referencias = models.BooleanField(null=True, blank=True)
    comentarios = models.TextField(null=True, blank=True)
    aceptado = models.BooleanField(default=False)

    def __str__(self):
        return f"Revisado: {self.revisado} - Documento: {self.documento_alumno.titulo}"

    def get_titulo_adecuado_display(self):
        return "Sí" if self.titulo_adecuado else "No"

    def get_objetivos_planteados_display(self):
        return "Sí" if self.objetivos_planteados else "No"

    def get_referencias_correctas_display(self):
        return "Sí" if self.referencias_correctas else "No"

    def get_errores_ortograficos_display(self):
        return "Sí" if self.errores_ortograficos else "No"

    def get_normas_formato_display(self):
        return "Sí" if self.normas_formato else "No"

    def get_metodologia_descrita_display(self):
        return "Sí" if self.metodologia_descrita else "No"

    def get_suficientes_referencias_display(self):
        return "Sí" if self.suficientes_referencias else "No"
    

alumnos/views.py
# alumnos/views.py
from django.views.generic import TemplateView
from .mixins import AlumnoRequiredMixin
from django.shortcuts import render, redirect

from django.http import JsonResponse
import json
# Importamos el modelo
from administracion.models import FormaTitulacion
from administracion.models import MaterialApoyo
from administracion.models import Documento
from administracion.models import RevisarPropuesta
# Importar vistas genéricas personalizadas
from django.views import View
from .subir_pre_alumno import upload_pdf
from django.db.models import Q
from django.views.generic import TemplateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import ProcesoTitulacion, DocumentoPropuestaAlumno, SinodalAsignado
from .forms import DocumentoPropuestaAlumnoForm
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
import spacy
from administracion.utils import upload_pdf_admin
from administracion.forms import DocumentoForm
from django.urls import reverse_lazy

class AlumnosHomeView(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/home.html'

class BuscarPorTipo(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/buscar_por_tipo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tipo = self.request.GET.get('tipo')
        if tipo:
            context['trabajos'] = Documento.objects.filter(tipo=tipo)
        else:
            context['trabajos'] = Documento.objects.none()
        return context

class BuscarPorPalabra(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/buscar_por_palabra.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        palabra = self.request.GET.get('palabra')
        if palabra:
            context['trabajos'] = Documento.objects.filter(
                Q(nombre__icontains=palabra) | 
                Q(resumen__icontains=palabra) | 
                Q(palabras_clave__icontains=palabra)
            )
        else:
            context['trabajos'] = Documento.objects.none()
        return context

class BuscarPorAño(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/buscar_por_año.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        año = self.request.GET.get('año')
        if año:
            try:
                # Extraer solo el año
                año = int(año.split('-')[0])
                context['trabajos'] = Documento.objects.filter(fecha_elaboracion__year=año)
            except ValueError:
                context['trabajos'] = Documento.objects.none()
        else:
            context['trabajos'] = Documento.objects.none()
        return context

class BusquedaAvanzada(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/busqueda_avanzada.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = Q()

        palabra_b = self.request.GET.get('palabra')
        autor_b = self.request.GET.get('autor')
        documento_b = self.request.GET.get('documento')
        docente_b = self.request.GET.get('docente')
        sinodal_b = self.request.GET.get('sinodal')
        convocatoria_b = self.request.GET.get('convocatoria')
        tipo_b = self.request.GET.get('tipo')
        año_b = self.request.GET.get('año')

        if palabra_b:
            query &= Q(nombre__icontains=palabra_b) | Q(resumen__icontains=palabra_b) | Q(palabras_clave__icontains=palabra_b)
        if autor_b:
            query &= Q(nombre_autor__icontains=autor_b)
        if documento_b:
            query &= Q(nombre__icontains=documento_b)
        if docente_b:
            query &= Q(sinodales__icontains=docente_b)
        if sinodal_b:
            query &= Q(sinodales__icontains=sinodal_b)
        if convocatoria_b:
            query &= Q(convocatoria_titulacion__icontains=convocatoria_b)
        if tipo_b:
            query &= Q(tipo=tipo_b)
        if año_b:
            try:
                # Extraer solo el año
                año = int(año_b.split('-')[0])
                query &= Q(fecha_elaboracion__year=año)
            except ValueError:
                pass

        context['trabajos'] = Documento.objects.filter(query)
        return context

# Cargar el modelo de spaCy
pln = spacy.load('es_core_news_sm')

def procesar_texto(texto):
    doc = pln(texto)
    noun_chunks = [chunk.text for chunk in doc.noun_chunks]
    return noun_chunks

class BuscarLenguajeNatural(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/busqueda_lenguaje_natural.html'

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        trabajos = []
        if query:
            # Procesar el texto de búsqueda
            noun_chunks = procesar_texto(query)
            print(f"Noun chunks: {noun_chunks}")
            # Buscar en los documentos
            documentos = Documento.objects.all()
            for doc in documentos:
                for chunk in noun_chunks:
                    if chunk in doc.palabras_clave:
                        trabajos.append(doc)
                        break
            print(f"Documentos encontrados: {trabajos}")
        return render(request, self.template_name, {'trabajos': trabajos})
    
class AlumnosBuscar(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/buscar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ver_todo = self.request.GET.get('ver_todo')
        
        if ver_todo == '1':
            context['trabajos'] = Documento.objects.all()
        else:
            context['trabajos'] = Documento.objects.none()
        
        return context

class AlumnosVerTrabajo(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/ver_trabajo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        documento_id = self.kwargs['pk']
        context['documento'] = Documento.objects.get(id=documento_id)
        return context


class AlumnosPreguntas(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/preguntas_frecuentes.html'

class AlumnosSubirDocumentos(TemplateView):
    template_name = 'alumnos/subir_documento.html'

    
class AlumnosTitulacion(AlumnoRequiredMixin,TemplateView):
    template_name = 'alumnos/titulacion.html'
    
# Todo para la titulación
class AlumnosTitulacionCalendario(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/titulacion/calendario_titulacion.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['convocatorias'] = FormaTitulacion.objects.all()
        return context
    
class AlumnosTitulacionConvocatoria(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/titulacion/convocatorias_titulacion.html'
class AlumnosTitulacionForma(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/titulacion/formas_titulacion.html'


class AlumnosTitulacionEstatus(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/titulacion/estatus_titulacion.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener o crear el proceso de titulación del usuario autenticado
        proceso, created = ProcesoTitulacion.objects.get_or_create(user=self.request.user)
        
        # Obtener el documento de propuesta del alumno
        documento = DocumentoPropuestaAlumno.objects.filter(alumno=self.request.user).first()
        
        # Verificar el estado de 'enviado', 'aceptado' y 'sinodales'
        if documento:
            if documento.enviado:
                proceso.enviar_propuesta = True
            if hasattr(documento, 'revisarpropuesta') and documento.revisarpropuesta.aceptado:
                proceso.resultado_propuesta = True
            if documento.sinodales:
                proceso.desarrollo_proyecto = True
        
        context['proceso'] = proceso
        return context


class AlumnosTitulacionMaterial(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/titulacion/material_apoyo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['guias'] = MaterialApoyo.objects.filter(tipo='Guía')
        context['formularios'] = MaterialApoyo.objects.filter(tipo='Formato')
        context['ejemplos'] = MaterialApoyo.objects.filter(tipo='Ejemplo')
        return context


class AlumnosInformacion(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/informacion_alumnos.html'


class AlumnosCambiarContrasena(View):
    def post(self, request):
        user = request.user
        data = json.loads(request.body)
        old_password = data.get('old_password', '')
        new_password = data.get('new_password', '')

        if not user.check_password(old_password):
            return JsonResponse({'status': 'error', 'message': 'Contraseña antigua incorrecta'}, status=403)

        if new_password:
            user.set_password(new_password)
        user.save()

        return JsonResponse({'status': 'ok', 'message': 'Contraseña cambiada con éxito'})
    

# -------------------Proceso de titulación-----------------------------------------

class AlumnosProcesoTitulacionInfo(AlumnoRequiredMixin, TemplateView):
    template_name = 'alumnos/proceso_titulacion/informacion.html'

class ActualizarVerInfo(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        # Obtener o crear el proceso de titulación del usuario autenticado
        proceso, created = ProcesoTitulacion.objects.get_or_create(user=request.user)
        proceso.ver_info = 1

alumnos/templates/alumnos/buscar.html
{% extends "base_generic_alumnos.html" %}

{% block content %}
<style>
  /* Ocultar la tabla al inicio */
.tabla-oculta {
    display: none;
}

/* Estilos básicos para los botones de opciones de búsqueda */
.Opciones_de_busqueda {
    display: flex;
    justify-content: center; /* Alinear los botones al centro */
    gap: 30px; /* Espaciado entre los botones */
    margin-top: 20px;
}

.Opciones_de_busqueda .btn {
    display: flex; /* Para centrar el contenido del botón */
    align-items: center; /* Centrar verticalmente */
    justify-content: center; /* Centrar horizontalmente */
    width: 200px;
    padding: 10px;
    text-align: center;
    background-color: #6b1640;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    font-size: 1.2rem;
}

.Opciones_de_busqueda .btn:hover {
    background-color: white;
    color: #6b1640;
    border: none;
}

/* Transformar a mayúsculas */
.uppercase {
    text-transform: uppercase;
}

table {
    margin-top: 50px;
}

</style>
<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <h1 >Buscar trabajos.</h1>
    <p class="letra_preguntas">Seleccione una opción para realizar la búsqueda:</p>
  
    <div class="Opciones_de_busqueda">
      <a href="{% url 'alumnos:buscar_por_tipo' %}" class="btn btn-primary">Buscar por Tipo</a>
      <a href="{% url 'alumnos:buscar_por_palabra' %}" class="btn btn-primary">Buscar por Palabra</a>
      <a href="{% url 'alumnos:buscar_por_año' %}" class="btn btn-primary">Buscar por Año</a>
      <a href="{% url 'alumnos:busqueda_avanzada' %}" class="btn btn-primary">Búsqueda Avanzada</a>
      <a href="{% url 'alumnos:buscar_lenguaje_natural' %}" class="btn btn-primary">Lenguaje natural</a>
      <button onclick="mostrarTodo()" class="btn btn-primary">Ver Todo</button>
    </div>
  
    <div id="tabla-resultados" class="tabla-oculta">
      <table>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Nombre Autor</th>
            <th>Fecha</th>
            <th>Ver información</th>
          </tr>
        </thead>
        <tbody id="resultadosBusqueda">
          {% for trabajo in trabajos %}
          <tr>
            <td class="uppercase">{{ trabajo.nombre }}</td>
            <td>{{ trabajo.nombre_autor }}</td>
            <td>{{ trabajo.fecha_elaboracion }}</td>
            <td><a href="{% url 'alumnos:ver_trabajo' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  function mostrarTodo() {
    window.location.href = "{% url 'alumnos:buscar' %}?ver_todo=1";
  }

  document.addEventListener("DOMContentLoaded", function() {
    const urlParams = new URLSearchParams(window.location.search);
    const verTodo = urlParams.get('ver_todo');

    if (verTodo === '1') {
      document.getElementById('tabla-resultados').classList.remove('tabla-oculta');
    }
  });
</script>

{% endblock %}

alumnos/templates/alumnos/buscar_por_año.html
{% extends "base_generic_alumnos.html" %}

{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #6b1640;
    color: white;
    font-size: 1.2rem;
}

.transparent-form {
  background: transparent;
  padding: 20px;
  border-radius: 10px;
}

.transparent-form label,
.transparent-form input,
.transparent-form button {
  display: block;
  width: 100%;
  margin-bottom: 10px;
}

.transparent-form .btn {
  width: 100px;
  margin: 0 auto;
  display: block;
}

.transparent-form input {
  padding: 5px;
  font-size: 16px;
}

.transparent-form .btn {
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  text-align: center;
}
</style>
<div id="fondo">
    <div class="contenedor_principal letra_texto">
      <a href="{% url 'alumnos:buscar' %}" class="letra_titulos">Regresar</a>
        <h1>Buscar por Año</h1>
        <form method="get" action="{% url 'alumnos:buscar_por_año' %}" class="transparent-form">
          <label for="inputAño">Seleccione un año:</label>
          <input type="date" id="inputAño" name="año" placeholder="YYYY">
          <button type="submit" class="btn">Buscar</button>
        </form>
        
      
        <table>
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Nombre Autor</th>
              <th>Fecha</th>
              <th>Ver información</th>
            </tr>
          </thead>
          <tbody>
            {% for trabajo in trabajos %}
            <tr>
              <td>{{ trabajo.nombre }}</td>
              <td>{{ trabajo.nombre_autor }}</td>
              <td>{{ trabajo.fecha_elaboracion }}</td>
              <td><a href="{% url 'alumnos:ver_trabajo' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>
{% endblock %}

alumnos/templates/alumnos/buscar_por_palabra.html
{% extends "base_generic_alumnos.html" %}

{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #6b1640;
    color: white;
    font-size: 1.2rem;
}

.transparent-form {
  background: transparent;
  padding: 20px;
  border-radius: 10px;
}

.transparent-form label,
.transparent-form input,
.transparent-form button {
  display: block;
  width: 100%;
  margin-bottom: 10px;
}

.transparent-form .btn {
  width: 100px;
  margin: 0 auto;
  display: block;
}

.transparent-form input {
  padding: 5px;
  font-size: 16px;
}

.transparent-form .btn {
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  text-align: center;
}


</style>
<div id="fondo">
    <div class="contenedor_principal letra_texto">
      <a href="{% url 'alumnos:buscar' %}" class="letra_titulos">Regresar</a>
        <h1>Buscar por Palabra</h1>
        <form method="get" action="{% url 'alumnos:buscar_por_palabra' %}" class="transparent-form">
          <label for="inputPalabra">Ingrese una palabra o frase:</label>
          <input type="text" id="inputPalabra" name="palabra">
          <button type="submit" class="btn">Buscar</button>
        </form>
      
        <table>
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Nombre Autor</th>
              <th>Fecha</th>
              <th>Ver información</th>
            </tr>
          </thead>
          <tbody>
            {% for trabajo in trabajos %}
            <tr>
              <td>{{ trabajo.nombre }}</td>
              <td>{{ trabajo.nombre_autor }}</td>
              <td>{{ trabajo.fecha_elaboracion }}</td>
              <td><a href="{% url 'alumnos:ver_trabajo' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>
{% endblock %}

alumnos/templates/alumnos/buscar_por_tipo.html
{% extends "base_generic_alumnos.html" %}

{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #6b1640;
    color: white;
    font-size: 1.2rem;
}

.transparent-form {
  background: transparent;
  padding: 20px;
  border-radius: 10px;
}

.transparent-form label,
.transparent-form input,
.transparent-form button {
  display: block;
  width: 100%;
  margin-bottom: 10px;
}

.transparent-form .btn {
  width: 100px;
  margin: 0 auto;
  display: block;
}

.transparent-form input {
  padding: 5px;
  font-size: 16px;
}

.transparent-form .btn {
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  text-align: center;
}


</style>
<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <a href="{% url 'alumnos:buscar' %}" class="letra_titulos">Regresar</a>
    <h1>Buscar por Tipo</h1>
    <form method="get" action="{% url 'alumnos:buscar_por_tipo' %}" class="transparent-form">
      <label for="selectTipo">Seleccione un tipo:</label>
      <select id="selectTipo" name="tipo">
        <option value="TT">Trabajo Terminal</option>
        <option value="AR">Artículo</option>
        <option value="TS">Tesis</option>
        <option value="OT">Otro</option>
      </select>
      <button type="submit" class="btn">Buscar</button>
    </form>
  
    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Nombre Autor</th>
          <th>Fecha</th>
          <th>Ver información</th>
        </tr>
      </thead>
      <tbody>
        {% for trabajo in trabajos %}
        <tr>
          <td>{{ trabajo.nombre }}</td>
          <td>{{ trabajo.nombre_autor }}</td>
          <td>{{ trabajo.fecha_elaboracion }}</td>
          <td><a href="{% url 'alumnos:ver_trabajo' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

alumnos/templates/alumnos/home.html
{% extends "base_generic_alumnos.html" %}
{% load static %}
{% block content %}
<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <div style="text-align: center;">
      <h1>Bienvenido al Repositorio de Trabajos Académicos - Alumnos</h1>
      <h2 class="letra_titulos">Accede, busca y comparte conocimiento</h2>
    </div>  
  </div>
</div>
{% endblock %}

alumnos/templates/alumnos/titulacion.html
{% extends "base_generic_alumnos.html" %}

{% block content %}
  <div id="fondo">
    <h1>Todo para la titulación de alumnos</h1>
  </div>
{% endblock %}