Aeneta/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),  # Incluye las URLs de la aplicación usuarios
    path('', CustomLoginView.as_view(), name='login'),  # El path vacío redirige al login
    path('administracion/', include('administracion.urls', namespace='administracion')),  # Incluye las URLs con el namespace
    path('alumnos/', include('alumnos.urls', namespace='alumnos')),
    path('visitante/', include(('visitante.urls', 'visitante'), namespace='visitante')),
    path('docente/', include('docente.urls', namespace='docente')),
    # ... cualquier otra ruta que necesites ...
]

visitante/urls.py
# visitante/urls.py
from django.urls import path
from .views import VisitanteHomeView, VisitanteCbuscarView, VisitanteContactoView, VisitantePfrecuentesView, VisitanteBuscarView, VisitanteBuscarPorAño, VisitanteBuscarPorPalabra, VisitanteBuscarPorTipo, VisitanteBusquedaAvanzada, VisitanteVerTrabajo, VsitanteBuscarLenguajeNatural
from . import views

app_name = 'visitante'

urlpatterns = [
    path('home/', VisitanteHomeView.as_view(), name='home'),
    path('buscar/', VisitanteBuscarView.as_view(), name='buscar'), 
    path('como_buscar/', VisitanteCbuscarView.as_view(), name='como_buscar'),  
    path('preguntas_frecuentes/', VisitantePfrecuentesView.as_view(), name='preguntas_frecuentes'),  
    path('contactanos/', VisitanteContactoView.as_view(), name='contactanos'), 
    path('contact/', views.contact, name='contact'),
    path('buscar_por_año_visitante/', VisitanteBuscarPorAño.as_view(), name='buscar_por_año_visitante'), 
    path('buscar_por_palabra_visitante/', VisitanteBuscarPorPalabra.as_view(), name='buscar_por_palabra_visitante'),
    path('buscar_por_tipo_visitante/', VisitanteBuscarPorTipo.as_view(), name='buscar_por_tipo_visitante'),
    path('busqueda_avanzada_visitante/', VisitanteBusquedaAvanzada.as_view(), name='busqueda_avanzada_visitante'),
    path('busqueda_lenguaje_natural_visitante/', VsitanteBuscarLenguajeNatural.as_view(), name='busqueda_lenguaje_natural_visitante'),
    path('ver_trabajo_visitante/<int:pk>/', VisitanteVerTrabajo.as_view(), name='ver_trabajo_visitante'),
]

administracion/models.py
from django.db import models

class FormaTitulacion(models.Model):
    convocatoria = models.CharField(max_length=100)
    fecha_inicio = models.DateField()
    fecha_limite_entrega = models.DateField()
    descripcion = models.TextField()
    requisitos = models.TextField()
    documentos_a_entregar = models.TextField()

    def __str__(self):
        return self.convocatoria
    
class Documento(models.Model):
    TIPO_CHOICES = (
        ('TT', 'Trabajo Terminal'),
        ('AR', 'Artículo'),
        ('TS', 'Tesis'),
        ('OT', 'Otro'),
    )
    
    nombre = models.CharField(max_length=255)
    resumen = models.TextField()
    palabras_clave = models.CharField(max_length=255)
    nombre_autor = models.CharField(max_length=100)
    sinodales = models.CharField(max_length=255)
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES)
    fecha_elaboracion = models.DateField()
    convocatoria_titulacion = models.CharField(max_length=100)
    url = models.URLField(blank=True, null=True)  # Hacer el campo opcional

    def __str__(self):
        return self.nombre

class Seminario(models.Model):
    titulo = models.CharField(max_length=200)
    fecha = models.DateField()
    hora = models.TimeField()
    ubicacion = models.CharField(max_length=200)
    descripcion = models.TextField()
    presentador = models.CharField(max_length=100)
    temas = models.TextField()
    requisitos = models.TextField()
    creditos_academicos = models.DecimalField(max_digits=3, decimal_places=1)

    def __str__(self):
        return self.titulo


class MaterialApoyo(models.Model):
    TIPO_CHOICES = [
        ('Guia', 'Guía'),
        ('Formato', 'Formato'),
        ('Ejemplo', 'Ejemplo'),
    ]

    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
    nombre = models.CharField(max_length=255) 
    url = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.tipo} - {self.nombre}"

#Proceso de titulacion

class RevisarPropuesta(models.Model):
    documento_alumno = models.OneToOneField('alumnos.DocumentoPropuestaAlumno', on_delete=models.CASCADE)
    revisado = models.BooleanField(default=False)
    titulo_adecuado = models.BooleanField(null=True, blank=True)
    objetivos_planteados = models.BooleanField(null=True, blank=True)
    referencias_correctas = models.BooleanField(null=True, blank=True)
    errores_ortograficos = models.BooleanField(null=True, blank=True)
    normas_formato = models.BooleanField(null=True, blank=True)
    metodologia_descrita = models.BooleanField(null=True, blank=True)
    suficientes_referencias = models.BooleanField(null=True, blank=True)
    comentarios = models.TextField(null=True, blank=True)
    aceptado = models.BooleanField(default=False)

    def __str__(self):
        return f"Revisado: {self.revisado} - Documento: {self.documento_alumno.titulo}"

    def get_titulo_adecuado_display(self):
        return "Sí" if self.titulo_adecuado else "No"

    def get_objetivos_planteados_display(self):
        return "Sí" if self.objetivos_planteados else "No"

    def get_referencias_correctas_display(self):
        return "Sí" if self.referencias_correctas else "No"

    def get_errores_ortograficos_display(self):
        return "Sí" if self.errores_ortograficos else "No"

    def get_normas_formato_display(self):
        return "Sí" if self.normas_formato else "No"

    def get_metodologia_descrita_display(self):
        return "Sí" if self.metodologia_descrita else "No"

    def get_suficientes_referencias_display(self):
        return "Sí" if self.suficientes_referencias else "No"
    

visitante/models.py
from django.db import models

# Create your models here.

visitante/views.py
from django.views.generic import TemplateView
from django.shortcuts import redirect, render
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib import messages
from administracion.models import Documento
import spacy
from django.db.models import Q

class VisitanteHomeView(TemplateView):
    template_name = 'visitante/home.html'

class VisitanteVerTrabajo(TemplateView):
    template_name = 'visitante/ver_trabajo_visitante.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        documento_id = self.kwargs['pk']
        context['documento'] = Documento.objects.get(id=documento_id)
        return context
    
class VisitanteBuscarView(TemplateView): 
    template_name = 'visitante/buscar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ver_todo = self.request.GET.get('ver_todo')
        
        if ver_todo == '1':
            context['trabajos'] = Documento.objects.all()
        else:
            context['trabajos'] = Documento.objects.none()
        
        return context
    
class VisitanteBuscarPorTipo(TemplateView):
    template_name = 'visitante/buscar_por_tipo_visitante.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tipo = self.request.GET.get('tipo')
        if tipo:
            context['trabajos'] = Documento.objects.filter(tipo=tipo)
        else:
            context['trabajos'] = Documento.objects.none()
        return context

class VisitanteBuscarPorPalabra(TemplateView):
    template_name = 'visitante/buscar_por_palabra_visitante.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        palabra = self.request.GET.get('palabra')
        if palabra:
            context['trabajos'] = Documento.objects.filter(
                Q(nombre__icontains=palabra) | 
                Q(resumen__icontains=palabra) | 
                Q(palabras_clave__icontains=palabra)
            )
        else:
            context['trabajos'] = Documento.objects.none()
        return context

class VisitanteBuscarPorAño(TemplateView):
    template_name = 'visitante/buscar_por_año_visitante.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        año = self.request.GET.get('año')
        if año:
            try:
                # Extraer solo el año
                año = int(año.split('-')[0])
                context['trabajos'] = Documento.objects.filter(fecha_elaboracion__year=año)
            except ValueError:
                context['trabajos'] = Documento.objects.none()
        else:
            context['trabajos'] = Documento.objects.none()
        return context

class VisitanteBusquedaAvanzada(TemplateView):
    template_name = 'visitante/busqueda_avanzada_visitante.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = Q()

        palabra_b = self.request.GET.get('palabra')
        autor_b = self.request.GET.get('autor')
        documento_b = self.request.GET.get('documento')
        docente_b = self.request.GET.get('docente')
        sinodal_b = self.request.GET.get('sinodal')
        convocatoria_b = self.request.GET.get('convocatoria')
        tipo_b = self.request.GET.get('tipo')
        año_b = self.request.GET.get('año')

        if palabra_b:
            query &= Q(nombre__icontains=palabra_b) | Q(resumen__icontains=palabra_b) | Q(palabras_clave__icontains=palabra_b)
        if autor_b:
            query &= Q(nombre_autor__icontains=autor_b)
        if documento_b:
            query &= Q(nombre__icontains=documento_b)
        if docente_b:
            query &= Q(sinodales__icontains=docente_b)
        if sinodal_b:
            query &= Q(sinodales__icontains=sinodal_b)
        if convocatoria_b:
            query &= Q(convocatoria_titulacion__icontains=convocatoria_b)
        if tipo_b:
            query &= Q(tipo=tipo_b)
        if año_b:
            try:
                # Extraer solo el año
                año = int(año_b.split('-')[0])
                query &= Q(fecha_elaboracion__year=año)
            except ValueError:
                pass

        context['trabajos'] = Documento.objects.filter(query)
        return context

# Cargar el modelo de spaCy
pln = spacy.load('es_core_news_sm')

def procesar_texto(texto):
    doc = pln(texto)
    noun_chunks = [chunk.text for chunk in doc.noun_chunks]
    return noun_chunks

class VsitanteBuscarLenguajeNatural(TemplateView):
    template_name = 'visitante/busqueda_lenguaje_natural_visitante.html'

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        trabajos = []
        if query:
            # Procesar el texto de búsqueda
            noun_chunks = procesar_texto(query)
            print(f"Noun chunks: {noun_chunks}")
            # Buscar en los documentos
            documentos = Documento.objects.all()
            for doc in documentos:
                for chunk in noun_chunks:
                    if chunk in doc.palabras_clave:
                        trabajos.append(doc)
                        break
            print(f"Documentos encontrados: {trabajos}")
        return render(request, self.template_name, {'trabajos': trabajos})
   
class VisitanteCbuscarView(TemplateView): 
    template_name = 'visitante/como_buscar.html'

class VisitantePfrecuentesView(TemplateView): 
    template_name = 'visitante/preguntas_frecuentes.html'

class VisitanteContactoView(TemplateView): 
    template_name = 'visitante/contactanos.html'

def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        template = render_to_string('contacto.html', {
            'name': name,
            'email': email,
            'message': message
        })

        email = EmailMessage(
            subject,
            template,
            settings.EMAIL_HOST_USER,
            ['aeneta.re@gmail.com']
        )

        email.fail_silently = False
        email.send()

        messages.success(request,' Correo enviado con exito.')
        return redirect('visitante:contactanos')
    
    # si no es la solicitus esperada
    return render(request, 'visitante:home.html')

visitante/templates/visitante/buscar.html
{% extends "base_generic_visitante.html" %}
{%  load static %}
{% block content %}
<style>
  /* Ocultar la tabla al inicio */
.tabla-oculta {
    display: none;
}

/* Estilos básicos para los botones de opciones de búsqueda */
.Opciones_de_busqueda {
    display: flex;
    justify-content: center; /* Alinear los botones al centro */
    gap: 30px; /* Espaciado entre los botones */
    margin-top: 20px;
}

.Opciones_de_busqueda .btn {
    display: flex; /* Para centrar el contenido del botón */
    align-items: center; /* Centrar verticalmente */
    justify-content: center; /* Centrar horizontalmente */
    width: 200px;
    padding: 10px;
    text-align: center;
    background-color: #156082;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    font-size: 1.2rem;
}

.Opciones_de_busqueda .btn:hover {
    background-color: white;
    color: #156082;
    border: none;
}

/* Transformar a mayúsculas */
.uppercase {
    text-transform: uppercase;
}

table {
    margin-top: 50px;
}

</style>
<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <h1 >Buscar trabajos.</h1>
    <p class="letra_preguntas">Seleccione una opción para realizar la búsqueda:</p>
  
    <div class="Opciones_de_busqueda">
      <a href="{% url 'visitante:buscar_por_tipo_visitante' %}" class="btn btn-primary">Buscar por Tipo</a>
      <a href="{% url 'visitante:buscar_por_palabra_visitante' %}" class="btn btn-primary">Buscar por Palabra</a>
      <a href="{% url 'visitante:buscar_por_año_visitante' %}" class="btn btn-primary">Buscar por Año</a>
      <a href="{% url 'visitante:busqueda_avanzada_visitante' %}" class="btn btn-primary">Búsqueda Avanzada</a>
      <a href="{% url 'visitante:busqueda_lenguaje_natural_visitante' %}" class="btn btn-primary">Lenguaje natural</a>
      <button onclick="mostrarTodo()" class="btn btn-primary">Ver Todo</button>
    </div>
  
    <div id="tabla-resultados" class="tabla-oculta">
      <table>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Nombre Autor</th>
            <th>Fecha</th>
            <th>Ver información</th>
          </tr>
        </thead>
        <tbody id="resultadosBusqueda">
          {% for trabajo in trabajos %}
          <tr>
            <td class="uppercase">{{ trabajo.nombre }}</td>
            <td>{{ trabajo.nombre_autor }}</td>
            <td>{{ trabajo.fecha_elaboracion }}</td>
            <td><a href="{% url 'visitante:ver_trabajo_visitante' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  function mostrarTodo() {
    window.location.href = "{% url 'visitante:buscar' %}?ver_todo=1";
  }

  document.addEventListener("DOMContentLoaded", function() {
    const urlParams = new URLSearchParams(window.location.search);
    const verTodo = urlParams.get('ver_todo');

    if (verTodo === '1') {
      document.getElementById('tabla-resultados').classList.remove('tabla-oculta');
    }
  });
</script>

{% endblock %}

visitante/templates/visitante/buscar_por_año_visitante.html
{% extends "base_generic_visitante.html" %}
{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #156082;
    color: white;
    font-size: 1.2rem;
}

.transparent-form {
  background: transparent;
  padding: 20px;
  border-radius: 10px;
}

.transparent-form label,
.transparent-form input,
.transparent-form button {
  display: block;
  width: 100%;
  margin-bottom: 10px;
}

.transparent-form .btn {
  width: 100px;
  margin: 0 auto;
  display: block;
}

.transparent-form input {
  padding: 5px;
  font-size: 16px;
}

.transparent-form .btn {
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  text-align: center;
}
</style>
<div id="fondo">
    <div class="contenedor_principal letra_texto">
      <a href="{% url 'visitante:buscar' %}" class="letra_titulos">Regresar</a>
        <h1>Buscar por Año</h1>
        <form method="get" action="{% url 'visitante:buscar_por_año_visitante' %}" class="transparent-form">
          <label for="inputAño">Seleccione un año:</label>
          <input type="date" id="inputAño" name="año" placeholder="YYYY">
          <button type="submit" class="btn">Buscar</button>
        </form>
        
      
        <table>
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Nombre Autor</th>
              <th>Fecha</th>
              <th>Ver información</th>
            </tr>
          </thead>
          <tbody>
            {% for trabajo in trabajos %}
            <tr>
              <td>{{ trabajo.nombre }}</td>
              <td>{{ trabajo.nombre_autor }}</td>
              <td>{{ trabajo.fecha_elaboracion }}</td>
              <td><a href="{% url 'visitante:ver_trabajo_visitante' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>
{% endblock %}

visitante/templates/visitante/buscar_por_palabra_visitante.html
{% extends "base_generic_visitante.html" %}
{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #156082;
    color: white;
    font-size: 1.2rem;
}

.transparent-form {
  background: transparent;
  padding: 20px;
  border-radius: 10px;
}

.transparent-form label,
.transparent-form input,
.transparent-form button {
  display: block;
  width: 100%;
  margin-bottom: 10px;
}

.transparent-form .btn {
  width: 100px;
  margin: 0 auto;
  display: block;
}

.transparent-form input {
  padding: 5px;
  font-size: 16px;
}

.transparent-form .btn {
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  text-align: center;
}


</style>
<div id="fondo">
    <div class="contenedor_principal letra_texto">
      <a href="{% url 'visitante:buscar' %}" class="letra_titulos">Regresar</a>
        <h1>Buscar por Palabra</h1>
        <form method="get" action="{% url 'visitante:buscar_por_palabra_visitante' %}" class="transparent-form">
          <label for="inputPalabra">Ingrese una palabra o frase:</label>
          <input type="text" id="inputPalabra" name="palabra">
          <button type="submit" class="btn">Buscar</button>
        </form>
      
        <table>
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Nombre Autor</th>
              <th>Fecha</th>
              <th>Ver información</th>
            </tr>
          </thead>
          <tbody>
            {% for trabajo in trabajos %}
            <tr>
              <td>{{ trabajo.nombre }}</td>
              <td>{{ trabajo.nombre_autor }}</td>
              <td>{{ trabajo.fecha_elaboracion }}</td>
              <td><a href="{% url 'visitante:ver_trabajo_visitante' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>
{% endblock %}

visitante/templates/visitante/buscar_por_tipo_visitante.html
{% extends "base_generic_visitante.html" %}
{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #156082;
    color: white;
    font-size: 1.2rem;
}

.transparent-form {
  background: transparent;
  padding: 20px;
  border-radius: 10px;
}

.transparent-form label,
.transparent-form input,
.transparent-form button {
  display: block;
  width: 100%;
  margin-bottom: 10px;
}

.transparent-form .btn {
  width: 100px;
  margin: 0 auto;
  display: block;
}

.transparent-form input {
  padding: 5px;
  font-size: 16px;
}

.transparent-form .btn {
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  text-align: center;
}


</style>
<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <a href="{% url 'visitante:buscar' %}" class="letra_titulos">Regresar</a>
    <h1>Buscar por Tipo</h1>
    <form method="get" action="{% url 'visitante:buscar_por_tipo_visitante' %}" class="transparent-form">
      <label for="selectTipo">Seleccione un tipo:</label>
      <select id="selectTipo" name="tipo">
        <option value="TT">Trabajo Terminal</option>
        <option value="AR">Artículo</option>
        <option value="TS">Tesis</option>
        <option value="OT">Otro</option>
      </select>
      <button type="submit" class="btn">Buscar</button>
    </form>
  
    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Nombre Autor</th>
          <th>Fecha</th>
          <th>Ver información</th>
        </tr>
      </thead>
      <tbody>
        {% for trabajo in trabajos %}
        <tr>
          <td>{{ trabajo.nombre }}</td>
          <td>{{ trabajo.nombre_autor }}</td>
          <td>{{ trabajo.fecha_elaboracion }}</td>
          <td><a href="{% url 'visitante:ver_trabajo_visitante' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

visitante/templates/visitante/busqueda_avanzada_visitante.html
{% extends "base_generic_visitante.html" %}
{% block content %}
<style>
  .btn {
    padding: 10px;
    text-align: center;
    background-color: #156082;
    color: white;
    font-size: 1.2rem;
  }

  .transparent-form {
    background: white;
    padding: 20px;
    border-radius: 10px;
    width: 70%;
    margin: 0 auto;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  .transparent-form label,
  .transparent-form input,
  .transparent-form button {
    display: block;
    width: 100%;
    margin-bottom: 10px;
  }

  .transparent-form .btn {
    width: 100px;
    margin: 0 auto;
    display: block;
  }

  .transparent-form input {
    padding: 5px;
    font-size: 16px;
  }

  .transparent-form .btn {
    padding: 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    text-align: center;
  }

</style>

<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <a href="{% url 'visitante:buscar' %}" class="letra_titulos">Regresar</a>
    <h1>Búsqueda Avanzada</h1>
    <form method="get" action="{% url 'visitante:busqueda_avanzada_visitante' %}" class="transparent-form">
      <label for="inputMail">Nombre del autor</label>
      <input type="text" name="autor" placeholder="Ingrese el nombre del Autor" id="autor_b">
      <label for="inputND">Nombre del documento</label>
      <input type="text" name="documento" placeholder="Ingrese el nombre del Documento" id="docu_b">
      <label for="inputDocente">Nombre del Docente</label>
      <input type="text" name="docente" placeholder="Ingrese el nombre del Docente" id="docente_b">
      <label for="inputSinodal">Sinodal</label>
      <input type="text" name="sinodal" placeholder="Ingrese el nombre del sinodal" id="sinodal_b">
      <label for="inputConv0">Convocatoria</label>
      <input type="text" name="convocatoria" placeholder="Ingrese la convocatoria" id="convo_b">
      <br>
      <button type="submit" class="btn">Buscar</button>
    </form>

    <div class="table-container" id="table-container">
      <table>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Nombre Autor</th>
            <th>Fecha</th>
            <th>Ver información</th>
          </tr>
        </thead>
        <tbody>
          {% for trabajo in trabajos %}
          <tr>
            <td>{{ trabajo.nombre }}</td>
            <td>{{ trabajo.nombre_autor }}</td>
            <td>{{ trabajo.fecha_elaboracion }}</td>
            <td><a href="{% url 'visitante:ver_trabajo_visitante' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

visitante/templates/visitante/busqueda_lenguaje_natural_visitante.html
{% extends "base_generic_visitante.html" %}
{% block content %}
<style>
    .btn {
      padding: 10px;
      text-align: center;
      background-color: #156082;
      color: white;
      font-size: 1.2rem;
  }
  
  .transparent-form {
    background: transparent;
    padding: 20px;
    border-radius: 10px;
  }
  
  .transparent-form label,
  .transparent-form input,
  .transparent-form button {
    display: block;
    width: 100%;
    margin-bottom: 10px;
  }
  
  .transparent-form .btn {
    width: 100px;
    margin: 0 auto;
    display: block;
  }
  
  .transparent-form input {
    padding: 5px;
    font-size: 16px;
  }
  
  .transparent-form .btn {
    padding: 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    text-align: center;
  }
  
  
  </style>
<div id="fondo">
  <div class="contenedor_principal letra_texto">
    <a href="{% url 'visitante:buscar' %}" class="letra_titulos">Regresar</a>
    <h1>Procesamiento de Lenguaje Natural</h1>
    <form method="GET" action="{% url 'visitante:busqueda_lenguaje_natural_visitante' %}"  class="transparent-form">
      <input type="text" name="q" placeholder="Introduce texto">
      <button type="submit" class="btn">Buscar</button>
    </form>
{% if trabajos %}
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Nombre Autor</th>
        <th>Fecha</th>
        <th>Ver información</th>
      </tr>
    </thead>
    <tbody>
      {% for trabajo in trabajos %}
      <tr>
        <td>{{ trabajo.nombre }}</td>
        <td>{{ trabajo.nombre_autor }}</td>
        <td>{{ trabajo.fecha_elaboracion }}</td>
        <td><a href="{% url 'visitante:ver_trabajo_visitante' trabajo.id %}"><i class="gg-arrow-top-right-o"></i></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No se encontraron resultados.</p>
{% endif %}

</div>
</div>
{% endblock %}

visitante/templates/visitante/como_buscar.html
{% extends "base_generic_visitante.html" %}

{% block content %}
  <div id="fondo">
    <h1>La busqueda se realiza de las sigueintes formas</h1>
  </div>
{% endblock %}

visitante/templates/visitante/ver_trabajo_visitante.html
{% extends "base_generic_visitante.html" %}

{% block content %}
<div id="fondo">
  <div class="contenedor_principal letra_texto">
   <div>
    <a href="{% url 'visitante:buscar' %}" class="letra_titulos">Regresar</a>
    <h1 class="letra_titulos">{{ documento.nombre }}</h1>
    <p><strong>Resumen:</strong> {{ documento.resumen }}</p>
    <p><strong>Palabras Clave:</strong> {{ documento.palabras_clave }}</p>
    <p><strong>Nombre del Autor:</strong> {{ documento.nombre_autor }}</p>
    <p><strong>Sinodales:</strong> {{ documento.sinodales }}</p>
    <p><strong>Tipo:</strong> {{ documento.get_tipo_display }}</p>
    <p><strong>Fecha de Elaboración:</strong> {{ documento.fecha_elaboracion }}</p>
    <p><strong>Convocatoria de Titulación:</strong> {{ documento.convocatoria_titulacion }}</p>
    {% if documento.url %}
        {% with documento.url|cut:"https://drive.google.com/file/d/"|cut:"/view?usp=drivesdk" as file_id %}
        <iframe src="https://drive.google.com/file/d/{{ file_id }}/preview" width="100%" height="600px"></iframe>
        {% endwith %}
    {% endif %}
   </div>
  </div>
</div>
{% endblock %}